# Generated by Django 3.1.7 on 2021-02-24 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schule', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Schule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Schule.schule'),
            preserve_default=False,
        ),
    ]
