# Generated by Django 3.1.7 on 2021-02-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schule', '0001_initial'),
        ('users', '0004_auto_20210224_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Schule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Schule.schule'),
        ),
    ]
