# Generated by Django 3.1.7 on 2021-02-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schule', '0001_initial'),
        ('users', '0006_auto_20210224_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Schule',
            field=models.ManyToManyField(blank=True, to='Schule.Schule'),
        ),
    ]
