# Generated by Django 3.1.7 on 2021-02-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Kunden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Strasse', models.CharField(max_length=50)),
                ('Hausnummer', models.IntegerField()),
                ('Postleitzahl', models.IntegerField()),
                ('Stadt', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Addresse')),
                ('Kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kunden.kunden')),
            ],
            options={
                'verbose_name': 'Schule',
                'verbose_name_plural': 'Schulen',
            },
        ),
    ]
