# Generated by Django 3.1.7 on 2021-02-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fahrten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bezeichnung', models.CharField(max_length=250)),
                ('Von', models.CharField(max_length=50)),
                ('Nach', models.CharField(max_length=50)),
                ('Abfahrt', models.TimeField()),
                ('Ankunft', models.TimeField()),
                ('Mo', models.BooleanField()),
                ('Di', models.BooleanField()),
                ('Mi', models.BooleanField()),
                ('Do', models.BooleanField()),
                ('Fr', models.BooleanField()),
                ('zweiteWoche', models.BooleanField()),
                ('Startdatum', models.DateField()),
                ('gueltigab', models.DateField()),
                ('gueltigbis', models.DateField()),
                ('Schule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schule.schule')),
            ],
            options={
                'verbose_name': 'Fahrt',
                'verbose_name_plural': 'Fahrten',
            },
        ),
    ]
