# Generated by Django 3.1.7 on 2021-02-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fahrten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrten',
            name='Kuschikbezeichnung',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
