# Generated by Django 3.1.7 on 2021-02-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fahrten', '0003_auto_20210226_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fahrten',
            old_name='gueltigab',
            new_name='gueltig_ab',
        ),
        migrations.RenameField(
            model_name='fahrten',
            old_name='gueltigbis',
            new_name='gueltig_bis',
        ),
    ]
