# Generated by Django 3.1.7 on 2021-03-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fahrten', '0004_auto_20210226_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wochentag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wochentag', models.CharField(max_length=20, null=True, unique=True)),
                ('wochentagID', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Wochentag',
                'verbose_name_plural': 'Wochentage',
            },
        ),
        migrations.AddField(
            model_name='fahrten',
            name='Wochentage',
            field=models.ManyToManyField(blank=True, to='Fahrten.Wochentag'),
        ),
    ]
