# Generated by Django 3.1.7 on 2021-02-24 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Absagen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absagen',
            name='Absagezeitpunkt',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 18, 26, 14, 913625, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
