# Generated by Django 3.1.7 on 2021-02-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Absagen', '0002_absagen_absagezeitpunkt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absagen',
            options={'verbose_name': 'Absage', 'verbose_name_plural': 'Absagen'},
        ),
        migrations.AlterField(
            model_name='absagen',
            name='Absagezeitpunkt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
