# Generated by Django 3.1.7 on 2021-02-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fahrten', '0002_fahrten_kuschikbezeichnung'),
        ('Absagen', '0004_auto_20210224_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absagen',
            name='Name',
        ),
        migrations.AddField(
            model_name='absagen',
            name='Fahrt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Fahrten.fahrten'),
            preserve_default=False,
        ),
    ]
