# Generated by Django 3.1.7 on 2021-02-25 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Absagen', '0005_auto_20210224_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absagen',
            name='Absagezeitpunkt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 25, 13, 36, 28, 697458, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
